Add fbcheck script to enforce no new FindBugs errors. Add fbcount script to count errors per module. Add scmowner and scmrev commands to support svn, git, and hg. Modify existing scripts to use scm versions of commands.
git-svn-id: svn+ssh://svn.java.net/glassfish~svn/trunk@62249 6f3ba3e3-413c-0410-a8aa-90bee3ab43b5

diff --git a/findbugs/findbugstotext/src/scripts/scmowner b/findbugs/findbugstotext/src/scripts/scmowner
--- a/findbugs/findbugstotext/src/scripts/scmowner
+++ b/findbugs/findbugstotext/src/scripts/scmowner
@@ -1,8 +1,8 @@
-#!/bin/sh 
+#!/bin/bash 
 #
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
-# Copyright (c) 2010-2013 Oracle and/or its affiliates. All rights reserved.
+# Copyright (c) 2013 Oracle and/or its affiliates. All rights reserved.
 #
 # The contents of this file are subject to the terms of either the GNU
 # General Public License Version 2 only ("GPL") or the Common Development
@@ -40,50 +40,36 @@
 #
 
 #
-# svnowner - convert from line number back to person who last changed that line
+# scmowner - convert from line number back to person who last changed that line
 #
 #	input is of the form "file: line: text",
 #	output is of the form "owner: file: line: text".
 #
-perl -e '
+# determines the SCM system in use and calls the corresponding script
+#
 
-$tmp = "/tmp/co" . $$;
-
-line: while (<>) {
-	#if (/^\s/ || !/\S+:\s*\d+:/) {
-        #	next line;
-	#}
-	chop;	# strip newline
-	($file, $lineno, $text) = split(/:/, $_, 3);
-#	if (! -r $file) {
-#		unlink $tmp;
-#		die "cant open $file\n";
-#	}
-	if ($file ne $curfile ) {
-		$curfile = $file;
-		$fileok = 0;
-		# need -v option; otherwise svn 1.7 truncates user name
-		if (-r $file &&
-			(system("svn annotate --non-interactive " .
-				"--trust-server-cert -v $file >$tmp " .
-				"2>/dev/null </dev/null") / 256 == 0)) {
-			$fileok = 1;
-		}
-	}
-	if ($fileok) {
-		if ($lineno <= 0 ) { 
-			$lineno = 1;
-		}
-		$fline = `sed -n ${lineno}p $tmp`;
-		chop $fline;
-		#s/[0-9.]+ *\(([^ ]+) .*/\1/;
-		($owner = $fline) =~ s/[0-9.]+ *([^ ]+) .*/\1/;
-		$owner =~ s/^\s+//;
-	} else {
-		$owner =  "UNKNOWN";
-	}
-        
-	printf "%s: %s\n", $owner, $_;
-}
-unlink $tmp;
-'
+p=$PWD
+while :
+do
+	if [ -d .svn ]
+	then
+		scm=svn
+		break
+	elif [ -d .hg ]
+	then
+		scm=hg
+		break
+	elif [ -d .git ]
+	then
+		scm=git
+		break
+	fi
+	if [ . -ef / -o . -ef "$HOME" ]
+	then
+		echo "scmowner: can't determine SCM system"
+		exit 1
+	fi
+	cd ..
+done
+cd $p
+exec ${scm}owner "$@"
